In [1]:
import seaborn as sns
import pandas as pd
import sys
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

interactive(children=(IntSlider(value=179, description='h', max=359), IntSlider(value=49, description='s', max…

[array([0.94054458, 0.95945542, 0.95679586, 1.        ]),
 array([0.87363254, 0.90742758, 0.90267475, 1.        ]),
 array([0.80672051, 0.85539974, 0.84855364, 1.        ]),
 array([0.73741876, 0.80151376, 0.79249963, 1.        ]),
 array([0.67050672, 0.74948591, 0.73837852, 1.        ]),
 array([0.60120497, 0.69559993, 0.68232452, 1.        ]),
 array([0.53429294, 0.64357209, 0.62820341, 1.        ]),
 array([0.46499119, 0.58968611, 0.5721494 , 1.        ]),
 array([0.39807915, 0.53765827, 0.51802829, 1.        ]),
 array([0.33116712, 0.48563043, 0.46390718, 1.        ])]